// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.7.7.5
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace io.cloudevents
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	public partial class AvroCloudEvent : ISpecificRecord
	{
		public static Schema _SCHEMA = Schema.Parse(@"{""type"":""record"",""name"":""AvroCloudEvent"",""namespace"":""io.cloudevents"",""fields"":[{""name"":""attribute"",""type"":{""type"":""map"",""values"":[""null"",""boolean"",""int"",""string"",""bytes""]}},{""name"":""data"",""type"":[""bytes"",""null"",""boolean"",{""type"":""map"",""values"":[""null"",""boolean"",{""type"":""record"",""name"":""AvroCloudEventData"",""namespace"":""io.cloudevents"",""fields"":[{""name"":""value"",""type"":{""type"":""map"",""values"":[""null"",""boolean"",{""type"":""map"",""values"":""AvroCloudEventData""},{""type"":""array"",""items"":""AvroCloudEventData""},""double"",""string""]}}]},""double"",""string""]},{""type"":""array"",""items"":""AvroCloudEventData""},""double"",""string""]}],""version"":""1.0""}");
		private IDictionary<string,System.Object> _attribute;
		private object _data;
		public virtual Schema Schema
		{
			get
			{
				return AvroCloudEvent._SCHEMA;
			}
		}
		public IDictionary<string,System.Object> attribute
		{
			get
			{
				return this._attribute;
			}
			set
			{
				this._attribute = value;
			}
		}
		public object data
		{
			get
			{
				return this._data;
			}
			set
			{
				this._data = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.attribute;
			case 1: return this.data;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.attribute = (IDictionary<string,System.Object>)fieldValue; break;
			case 1: this.data = (System.Object)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
